In [1]:
import cv2
import numpy as np

In [2]:
background = np.zeros((400,400, 3)).astype(np.uint8)

cv2.line(background, 
    (150,150),
    (150,250),
    (200,1,100),
    5,
    cv2.FILLED
)

cv2.line(background, 
    (100,350),
    (200,350),
    (1,0,100),
    10,
    cv2.LINE_8
)

cv2.line(background, 
    (30,300),
    (100,180),
    (255,1,1),
    5,
    cv2.LINE_4
)

cv2.line(background, 
    (200,350),
    (150,50),
    (0,255,0),
    8,
    cv2.LINE_AA
)



cv2.imshow("background", background)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [3]:
cv2.rectangle(background,
    (50, 200),
    (200, 250),
    (0,1,250),
    

)

cv2.imshow("backgorund", background)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [4]:
cv2.circle(background,
    (100,100),
    50,
    (255,0,0),
    5,
    cv2.LINE_AA  
)

cv2.imshow("backgorund", background)
cv2.waitKey(0)
cv2.destroyAllWindows()

# METHOD EXTERNAL

In [21]:
img = cv2.imread('../footage/hierarchy.png')

img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret,thresh = cv2.threshold(img, 127, 255, cv2.THRESH_BINARY)

contours, hierarchy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)


In [6]:
hierarchy

array([[[ 1, -1, -1, -1],
        [ 2,  0, -1, -1],
        [-1,  1, -1, -1]]], dtype=int32)

In [25]:
for cnt in contours:
    cv2.drawContours(img, cnt, -1, (255,100,0), 15)

In [26]:
cv2.imshow("Drawing Contour - Method External", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# METHOD TREE

In [27]:
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)

In [28]:
hierarchy

array([[[ 7, -1,  1, -1],
        [-1, -1,  2,  0],
        [-1, -1,  3,  1],
        [-1, -1,  4,  2],
        [-1, -1,  5,  3],
        [ 6, -1, -1,  4],
        [-1,  5, -1,  4],
        [ 8,  0, -1, -1],
        [-1,  7, -1, -1]]], dtype=int32)

In [29]:
for cnt in contours:
    cv2.drawContours(img, cnt, -1, (255,100,0), 15)

In [31]:
cv2.imshow("Drawing Contour - Method Tree", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# METHOD CCOMP

retrieves all of the contours and organizes them into a two-level hierarchy.

In [32]:
contours, hierarchy = cv2.findContours(thresh, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_SIMPLE)

In [33]:
hierarchy

array([[[ 3, -1,  1, -1],
        [ 2, -1, -1,  0],
        [-1,  1, -1,  0],
        [ 5,  0,  4, -1],
        [-1, -1, -1,  3],
        [ 7,  3,  6, -1],
        [-1, -1, -1,  5],
        [ 8,  5, -1, -1],
        [-1,  7, -1, -1]]], dtype=int32)

In [34]:
for cnt in contours:
    cv2.drawContours(img, cnt, -1, (255,100,0), 15)

In [35]:
cv2.imshow("Drawing Contour - Method Tree", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Task
- Read noisy_text.png
- Convert to grayscale
- Apply thresholding,
- Find extream contour
- Draw contour

In [94]:
noisy_img = cv2.imread('../footage/noisy_text.png')
gray_noisy_img = cv2.cvtColor(noisy_img, cv2.COLOR_BGR2GRAY)

In [95]:
ret1, gray_noisy_img_th1 = cv2.threshold(gray_noisy_img, 100, 255, cv2.THRESH_BINARY)
ret2, gray_noisy_img_th2 = cv2.threshold(gray_noisy_img, 100, 255, cv2.THRESH_BINARY_INV)
ret3, gray_noisy_img_th3 = cv2.threshold(gray_noisy_img, 100, 255, cv2.THRESH_TRUNC)
ret4, gray_noisy_img_th4 = cv2.threshold(gray_noisy_img, 100, 255, cv2.THRESH_TOZERO)
ret5, gray_noisy_img_th5 = cv2.threshold(gray_noisy_img, 100, 255, cv2.THRESH_TOZERO_INV)

cv2.imshow("binary", gray_noisy_img_th1)
cv2.imshow("binary_inv", gray_noisy_img_th2)
cv2.imshow("trunc", gray_noisy_img_th3)
cv2.imshow("tozero", gray_noisy_img_th4)
cv2.imshow("tozero_inv", gray_noisy_img_th5)

cv2.waitKey(0)
cv2.destroyAllWindows()

hasil binary dan binary_inv paling baik, disini kita gunakan binary saja

In [96]:
cont, hier = cv2.findContours(gray_noisy_img_th2, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)
hier

array([[[ 1, -1, -1, -1],
        [ 2,  0, -1, -1],
        [ 3,  1, -1, -1],
        [ 4,  2, -1, -1],
        [ 5,  3, -1, -1],
        [ 6,  4, -1, -1],
        [-1,  5, -1, -1]]], dtype=int32)

In [97]:
for cnt in cont:
    cv2.drawContours(noisy_img, cnt, -1, (255,0,255), 5)

cv2.imshow("Contour result", noisy_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Contour Features
contour approximate

In [100]:
print("LUAS")
for cnt in cont:
    area = cv2.contourArea(cnt)
    print("Luas: %d pixel" % area)
print("\n==========================\n")
print("KELILING")
for cnt in cont:
    area = cv2.arcLength(cnt, True)
    print("Keliling: %d pixel" % area)
print("\n==========================\n")

LUAS
Luas: 12111 pixel
Luas: 12104 pixel
Luas: 10484 pixel
Luas: 16998 pixel
Luas: 9304 pixel
Luas: 10492 pixel
Luas: 7052 pixel


KELILING
Keliling: 775 pixel
Keliling: 776 pixel
Keliling: 782 pixel
Keliling: 505 pixel
Keliling: 723 pixel
Keliling: 722 pixel
Keliling: 459 pixel




In [107]:
img = cv2.imread('../footage/noisy_text.png')

gray_img = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

ret, thresh = cv2.threshold(gray_img, 100,255, cv2.THRESH_BINARY_INV)

contours, hierarcy = cv2.findContours(thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    epsilon = 0.001*cv2.arcLength(cnt,True)
    approx = cv2.approxPolyDP(cnt, epsilon, True)
    cv2.polylines(img,  [approx], True, (0,255,255), 5)

cv2.imshow("Contour Approximation", img)
cv2.waitKey(0)
cv2.destroyAllWindows()

# Bounding Rectangle

In [111]:
frame = img.copy()
for cnt in contours:
    x,y,w,h = cv2.boundingRect(cnt)
    cv2.rectangle(frame, (x,y), (x+w, y+h), (0,0,255), 3)

cv2.imshow("Rectangle Contour", frame)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [118]:
frame = img.copy()
for i,cnt in enumerate(contours):
    x,y,w,h = cv2.boundingRect(cnt)
    roi = frame[y:y+h, x:x+w]
    cv2.imshow("Contour-%d" % i,roi)

cv2.waitKey(0)
cv2.destroyAllWindows()

juga bisa disimpat di list dlu


In [123]:
frame = img.copy()
roi = []

for i,cnt in enumerate(contours):
    x,y,w,h = cv2.boundingRect(cnt)
    roi.append(frame[y:y+h , x:x+w])

for  i,item in enumerate(roi):
    cv2.imshow("image roi - %d" % i,item)
cv2.waitKey(0)
cv2.destroyAllWindows()

# KTP PHOTO DETECTION

In [134]:
ktp = cv2.imread('../footage/ktp1.jpg')
h_ktp,w_ktp,c = ktp.shape

gray_ktp = cv2.cvtColor(ktp, cv2.COLOR_BGR2GRAY)

ret , thresh = cv2.threshold(gray_ktp, 127, 255, cv2.THRESH_BINARY)

contours, hierarcy = cv2.findContours(thresh, cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)

for cnt in contours:
    x,y,w,h = cv2.boundingRect(cnt)

    aspectRatio = w/h
    heightRatio = h/h_ktp

    keepAspectRatio = aspectRatio > 0.7 and aspectRatio <0.9
    keepHeightRatio = heightRatio >0.4 and heightRatio <0.6

    if keepAspectRatio and keepHeightRatio :
        roi = ktp[y:y+h , x:x+w]
        cv2.rectangle(ktp, (x,y), (x+w, y+h), (255,0,0), 3)

        cv2.imshow("Binary Threshold", thresh)
        cv2.imshow("Cropped", roi)

cv2.imshow("Detected Photo", ktp)
cv2.waitKey(0)
cv2.destroyAllWindows()